#!/usr/bin/env python3
"""
casebook.py — the casebook's tool. See casebook/README.md for the format.

  check          validate every case file's invariants; exit 1 on violation
  index          regenerate INDEX.md deterministically (idempotent)
  new <slug> -t "Title"      create the next-numbered case from the template
  append <NNNN> <kind>       add the next entry skeleton to a case

No third-party dependencies — system Python 3 only.
"""

import datetime
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STATUSES = ("open", "diagnosed", "treated", "closed", "reopened")
KINDS = ("hypothesis", "failure", "option", "decision", "follow-up")

CASE_RE = re.compile(r"^(\d{4})-[a-z0-9][a-z0-9-]*\.md$")
TITLE_RE = re.compile(r"^# Case (\d{4}) — (.+)$")
ENTRY_RE = re.compile(r"^## (\d{4})\.(\d+) · (\d{4}-\d{2}-\d{2}) · ([a-z-]+)(?: — .+)?$")


def case_files():
    return sorted(f for f in os.listdir(HERE) if CASE_RE.match(f))


def parse(fname):
    """Parse one case file into (meta, entries, problems)."""
    cid = CASE_RE.match(fname).group(1)
    problems = []
    meta = {"id": cid, "file": fname, "title": None, "status": None,
            "opened": None, "links": "", "touches": ""}
    entries = []
    with open(os.path.join(HERE, fname)) as fh:
        lines = fh.read().splitlines()

    if not lines or not TITLE_RE.match(lines[0]):
        problems.append("first line must be '# Case NNNN — Title'")
    else:
        tid, title = TITLE_RE.match(lines[0]).groups()
        meta["title"] = title
        if tid != cid:
            problems.append("header id %s != filename id %s" % (tid, cid))

    for ln in lines[1:8]:                      # header block sits at the top
        m = re.match(r"^(status|opened|links|touches):\s*(.*)$", ln)
        if m:
            meta[m.group(1)] = m.group(2).strip()

    if meta["status"] not in STATUSES:
        problems.append("status %r not in %s" % (meta["status"], list(STATUSES)))
    try:
        datetime.date.fromisoformat(meta["opened"] or "")
    except ValueError:
        problems.append("opened: %r is not an ISO date" % meta["opened"])

    for ln in lines:
        if not ln.startswith("## "):
            continue
        m = ENTRY_RE.match(ln)
        if not m:
            problems.append("malformed entry heading: %r" % ln)
            continue
        eid, k, date, kind = m.group(1), int(m.group(2)), m.group(3), m.group(4)
        if eid != cid:
            problems.append("entry %s.%d belongs to case %s" % (eid, k, cid))
        if kind not in KINDS:
            problems.append("entry %s.%d kind %r not in %s" % (eid, k, kind, list(KINDS)))
        try:
            datetime.date.fromisoformat(date)
        except ValueError:
            problems.append("entry %s.%d date %r invalid" % (eid, k, date))
        entries.append((k, date, kind))

    ks = [k for k, _, _ in entries]
    if ks != list(range(1, len(ks) + 1)):
        problems.append("entry numbers %s are not sequential from 1" % ks)
    if not entries:
        problems.append("a case needs at least one entry")
    return meta, entries, problems


def cmd_check():
    bad = 0
    ids = {}
    for f in case_files():
        meta, _, problems = parse(f)
        if meta["id"] in ids:
            problems.append("duplicate case id (also %s)" % ids[meta["id"]])
        ids[meta["id"]] = f
        for p in problems:
            sys.stderr.write("%s: %s\n" % (f, p))
        bad += len(problems)
    print("casebook check: %d case(s), %d problem(s)" % (len(ids), bad))
    return 1 if bad else 0


def cmd_index():
    rows = []
    for f in case_files():
        meta, entries, _ = parse(f)
        last = max((d for _, d, _ in entries), default=meta["opened"])
        rows.append((meta["id"], meta["title"] or "?", meta["status"] or "?",
                     meta["opened"] or "?", last, len(entries), f))
    out = ["# Casebook index", "",
           "*Generated by `casebook.py index` — do not edit. "
           "One case per problem node; see [README.md](README.md).*", "",
           "| Case | Title | Status | Opened | Last entry | Entries |",
           "|---|---|---|---|---|---|"]
    for cid, title, status, opened, last, n, f in rows:
        out.append("| [%s](%s) | %s | %s | %s | %s | %d |"
                   % (cid, f, title, status, opened, last, n))
    path = os.path.join(HERE, "INDEX.md")
    text = "\n".join(out) + "\n"
    old = open(path).read() if os.path.exists(path) else None
    if old != text:
        open(path, "w").write(text)
        print("INDEX.md written (%d cases)" % len(rows))
    else:
        print("INDEX.md unchanged (%d cases)" % len(rows))
    return 0


def cmd_new(slug, title):
    if not re.match(r"^[a-z0-9][a-z0-9-]*$", slug):
        sys.stderr.write("slug must be lowercase-kebab\n")
        return 2
    nxt = max([int(CASE_RE.match(f).group(1)) for f in case_files()] or [0]) + 1
    cid = "%04d" % nxt
    fname = "%s-%s.md" % (cid, slug)
    today = datetime.date.today().isoformat()
    open(os.path.join(HERE, fname), "w").write(
        "# Case %s — %s\nstatus: open\nopened: %s\nlinks: \ntouches: \n\n"
        "## %s.1 · %s · hypothesis\n\n(what we believe, and why)\n"
        % (cid, title, today, cid, today))
    print("created %s" % fname)
    return 0


def cmd_append(cid, kind):
    if kind not in KINDS:
        sys.stderr.write("kind must be one of %s\n" % (KINDS,))
        return 2
    matches = [f for f in case_files() if f.startswith(cid + "-")]
    if len(matches) != 1:
        sys.stderr.write("no unique case %s\n" % cid)
        return 2
    _, entries, _ = parse(matches[0])
    k = len(entries) + 1
    today = datetime.date.today().isoformat()
    with open(os.path.join(HERE, matches[0]), "a") as fh:
        fh.write("\n## %s.%d · %s · %s\n\n\n" % (cid, k, today, kind))
    print("appended %s.%d (%s) to %s" % (cid, k, kind, matches[0]))
    return 0


def main(argv):
    args = argv[1:]
    if not args:
        sys.stderr.write(__doc__)
        return 2
    rc = 0
    while args:
        cmd = args.pop(0)
        if cmd == "check":
            rc = cmd_check() or rc
        elif cmd == "index":
            rc = cmd_index() or rc
        elif cmd == "new":
            slug = args.pop(0)
            title = slug
            if args[:1] == ["-t"]:
                args.pop(0)
                title = args.pop(0)
            return cmd_new(slug, title)
        elif cmd == "append":
            return cmd_append(args.pop(0), args.pop(0))
        else:
            sys.stderr.write("unknown command: %s\n%s" % (cmd, __doc__))
            return 2
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv))
